import type { LessonSeed } from "./pythonAdvanced";

/**
 * Authored debugging labs for the Python track: one diagnostic-and-repair lesson for each
 * chapter that previously had no lesson whose activity was finding and fixing a real defect.
 *
 * Every broken program, repaired program, and exercise solution below was executed with a
 * local CPython 3.11.2 interpreter and its documented output matched exactly, so the lesson
 * text describes observed behaviour and never an assumed or generated result.
 */
const pythonDebugLabs: Record<number, LessonSeed> = {
  // Chapter 3
  3: {
    title: "Debug lab: stop the search when the goal is met",
    minutes: 34,
    summary: "Find the first value that satisfies a rule and leave the loop instead of scanning the rest.",
    learningGoals: ["Recognise a loop that keeps running after its answer is found", "Choose break over continue for a first-match search", "Trace iteration by hand before editing the loop"],
    explanation: "A search loop should end as soon as its answer is known. continue skips the rest of the current iteration and lets the loop carry on, so a search written with continue keeps scanning and prints later matches the caller never asked for. break leaves the loop at that point, which is what a first-match search promises. The repair is small; the reading skill is noticing that the loop had no exit condition at all.",
    keywordNotes: ["break exits the loop immediately, while continue only skips the rest of the current iteration.", "A search loop's contract states whether it wants the first match or every match.", "Reading the loop's output by hand shows every line the broken version prints before you change anything."],
    examples: [
      {
        title: "The search that will not stop",
        code: 'values = [1, 4, 7, 9]\nfor value in values:\n    if value >= 4:\n        print(value)\n        continue',
        output: '4\n7\n9',
        explanation: "The loop has no exit, so every value that satisfies the rule is printed even though the requirement asked for the first one. continue is the culprit: it only ends the current iteration, so the loop is free to continue.",
        reasons: [
          "The list holds the values the search walks through in order.",
          "for takes each value in turn; nothing here can end the loop early.",
          "The condition selects the values that satisfy the search rule.",
          "A match is printed, which is correct for the first match.",
          "continue only skips the rest of this iteration, so the loop keeps running and the missing exit is never noticed here.",
        ],
      },
      {
        title: "Stop at the first match",
        code: 'values = [1, 4, 7, 9]\nfor value in values:\n    if value >= 4:\n        print(value)\n        break',
        output: '4',
        explanation: "break ends the loop on the same iteration that printed the answer, so the program does exactly the work the requirement described and nothing more.",
        reasons: [
          "The same list is searched, so the repair changes only the loop's exit.",
          "The loop still visits values in order until the rule matches.",
          "The rule that decides a match is unchanged.",
          "The first match is printed exactly as before.",
          "break now ends the loop instead of skipping to the next iteration, which is the whole repair.",
        ],
      },
    ],
    exercise: {
      prompt: "Print the first score that is at least 4 from scores = [1, 4, 7, 9], then stop the loop.",
      starterCode: '# Stop the loop after the first match\nscores = [1, 4, 7, 9]\n',
      solution: 'scores = [1, 4, 7, 9]\nfor score in scores:\n    if score >= 4:\n        print(score)\n        break',
      solutionExplanation: "The loop exits on the first match, so the printed value is the single result the search promises instead of every match it walks past.",
      testCases: [{ label: "First-match search", expected: '4' }],
      hints: ["The list already exists in the starter code.", "Print inside the if block.", "Use break to leave the loop after printing."],
    },
    recap: ["A first-match search needs an exit, and break is that exit.", "continue and break are not interchangeable: one ends an iteration, the other ends the loop.", "Tracing the loop by hand reveals extra output before any edit is made."],
    decisionGuide: [
      { use: "break for a first-match search", insteadOf: "continue after printing the match", reason: "continue only skips the rest of that iteration, so the loop keeps producing matches the requirement did not ask for." },
      { use: "reading the loop's output by hand", insteadOf: "guessing which line is wrong", reason: "Printing the sequence the loop actually produces shows the missing exit immediately." },
    ],
  },
  // Chapter 4
  4: {
    title: "Debug lab: a default value that is shared",
    minutes: 33,
    summary: "Repair a function whose default argument is reused between calls.",
    learningGoals: ["Recognise a mutable default argument", "Use None as a sentinel that creates a fresh value", "Explain why the second call saw the first call's data"],
    explanation: "Default values are evaluated once, when the function is defined, so a mutable default is created a single time and reused by every call that omits the argument. The first call looks correct, which is what makes this bug expensive: the state leaks silently until a later call returns data the caller never supplied. The repair is the None sentinel, which creates a new list on each call.",
    keywordNotes: ["A default argument is evaluated once at definition time, not on every call.", "None is the conventional sentinel for 'the caller did not supply this value'.", "A function that accumulates state should say whether it mutates the caller's object or a private copy."],
    examples: [
      {
        title: "The list that remembers the last call",
        code: 'def collect(item, items=[]):\n    items.append(item)\n    return items\nprint(collect("read"))\nprint(collect("write"))',
        output: '[\'read\']\n[\'read\', \'write\']',
        explanation: "The empty list was created once when the function was defined, so both calls share it. The second call appends to the list the first call already filled, which is why write returns both items.",
        reasons: [
          "def defines the function and evaluates the default list once, at this line.",
          "append mutates whichever list was passed in, or the shared default when the caller omits it.",
          "return hands that same list back to the caller.",
          "The first call omits items, so it appends to the shared default and prints one item.",
          "The second call omits items again and receives the same list, which now holds the first call's value as well.",
        ],
      },
      {
        title: "A fresh list for every call",
        code: 'def collect(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items\nprint(collect("read"))\nprint(collect("write"))',
        output: '[\'read\']\n[\'write\']',
        explanation: "None is immutable, so sharing it costs nothing. Each call that omits the argument creates its own list, and each printed result now contains only the item that call supplied.",
        reasons: [
          "The default is now None, which carries no state between calls.",
          "The guard asks whether the caller supplied a list of their own.",
          "A new list is created for this call only, which is the repair.",
          "append writes to that private list, or to the caller's list when one was passed.",
          "The result is returned as before.",
          "The first call prints the one item it added.",
          "The second call prints its own list, so no state leaked from the first call.",
        ],
      },
    ],
    exercise: {
      prompt: "Define collect(item, items=None) that appends item to a fresh list when items is None. Print collect(\"read\") and then collect(\"write\").",
      starterCode: '# Create a fresh list when the caller passes nothing\n',
      solution: 'def collect(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items\nprint(collect("read"))\nprint(collect("write"))',
      solutionExplanation: "Each call builds a fresh list because the sentinel is None, so the second caller receives only its own item.",
      testCases: [{ label: "Two independent calls", expected: '[\'read\']\n[\'write\']' }],
      hints: ["Use None as the default.", "Check for None inside the function before appending.", "Return the list so print can display it."],
    },
    recap: ["A default argument is created once and reused by every call that omits it.", "None is a safe sentinel because it carries no mutable state.", "The bug is invisible on the first call, so tests must call the function twice."],
    decisionGuide: [
      { use: "None as a sentinel for 'not supplied'", insteadOf: "a mutable default such as an empty list", reason: "The mutable default is shared by every call, so state leaks in a way that is easy to miss." },
      { use: "calling a function twice in a test", insteadOf: "checking only the first call", reason: "The shared default only misbehaves on the second call, which a single-call test never reaches." },
    ],
  },
  // Chapter 5
  5: {
    title: "Debug lab: changing a dictionary while reading it",
    minutes: 35,
    summary: "Repair the loop that deletes from the same collection it is iterating.",
    learningGoals: ["Read the RuntimeError and name what changed during iteration", "Collect the keys to delete before touching the dictionary", "Choose a comprehension when the rule is a filter"],
    explanation: "A for loop over a dictionary asks the dictionary for its next key on every step, so removing an entry while that loop is running invalidates the cursor and Python stops with RuntimeError. The durable habit is to separate the decision from the change: compute the keys that should go, then delete them in a second, short step.",
    keywordNotes: ["Deleting during iteration raises RuntimeError: dictionary changed size during iteration.", "A list comprehension can capture the keys that match a removal rule without changing the dictionary.", "Separating the decision from the change keeps both steps readable and testable."],
    examples: [
      {
        title: "Deleting while the loop is reading",
        code: 'counts = {"read": 2, "test": 0, "build": 1}\ntry:\n    for topic in counts:\n        if counts[topic] == 0:\n            del counts[topic]\nexcept RuntimeError as error:\n    print(type(error).__name__)',
        output: 'RuntimeError',
        explanation: "The loop asked the dictionary for its next key after the deletion had changed the dictionary's size, and Python refuses that operation rather than returning a confusing result. The failure is honest, but it happens inside the loop instead of at a boundary the code controls.",
        reasons: [
          "The dictionary holds the counts, including the zero this code wants to remove.",
          "try begins a block so the failure can be reported as evidence instead of a traceback.",
          "The loop reads the dictionary directly, which is what makes the deletion unsafe here.",
          "The rule selects the entries whose count reached zero.",
          "del changes the dictionary's size while the loop is still asking for keys.",
          "Python stops the loop with RuntimeError because the collection changed during iteration.",
          "The except clause turns that failure into one readable line of evidence.",
        ],
      },
      {
        title: "Decide first, then delete",
        code: 'counts = {"read": 2, "test": 0, "build": 1}\nfor topic in [name for name, count in counts.items() if count == 0]:\n    del counts[topic]\nprint(counts)',
        output: '{\'read\': 2, \'build\': 1}',
        explanation: "The comprehension builds a separate list of the keys to remove, so the loop iterates that list while the dictionary is free to change. Deleting now happens after every decision was made, and the loop ends normally.",
        reasons: [
          "The comprehension reads the dictionary once and produces the keys whose count is zero, and the loop walks that list instead.",
          "The loop now walks that list, so the dictionary is never read while it changes.",
          "del removes the key the decision already selected.",
          "print shows the entries that survive, which is the requirement.",
        ],
      },
    ],
    exercise: {
      prompt: "Delete every entry whose count is 0 from counts = {\"read\": 2, \"test\": 0, \"build\": 1}. Print the result.",
      starterCode: 'counts = {"read": 2, "test": 0, "build": 1}\n# Remove the zero counts without changing the dictionary during iteration\n',
      solution: 'counts = {"read": 2, "test": 0, "build": 1}\nfor topic in [name for name, count in counts.items() if count == 0]:\n    del counts[topic]\nprint(counts)',
      solutionExplanation: "The keys are collected before anything is removed, so the loop iterates a stable list while the dictionary loses only the zeroed entries.",
      testCases: [{ label: "Deletion without a RuntimeError", expected: '{\'read\': 2, \'build\': 1}' }],
      hints: ["Build the list of keys first.", "Delete inside a second loop over that list.", "Print the dictionary after the deletions."],
    },
    recap: ["A dictionary cannot change size while a loop is reading it.", "Collecting the affected keys first separates the decision from the change.", "A comprehension is a concise way to state the removal rule."],
    decisionGuide: [
      { use: "collecting the keys, then deleting", insteadOf: "deleting inside the iteration", reason: "The second loop is safe because the collection it walks is not the one being modified." },
      { use: "a comprehension for the rule", insteadOf: "a loop that mutates as it decides", reason: "Stating the rule separately keeps the deletion step short and trivially correct." },
    ],
  },
  // Chapter 6
  6: {
    title: "Debug lab: a pattern that matches too much",
    minutes: 32,
    summary: "Repair a validator that accepted a substring instead of the whole value.",
    learningGoals: ["Distinguish search from fullmatch", "Repair a validation rule that passed invalid input", "Explain why a passing test is not proof the rule is complete"],
    explanation: "re.search answers 'does this pattern appear anywhere', while re.fullmatch answers 'is this entire string the pattern'. A validator written with search accepts any value that merely contains a valid-looking fragment, which is why PY-101 extra passed. The repair is one function change, and the lesson is that a rule's job is to reject, so the test data must include values that should fail.",
    keywordNotes: ["re.search finds the pattern anywhere in the text; re.fullmatch requires the whole string to match.", "A validator that only ever sees valid input proves nothing about its rejections.", "None from a failed fullmatch is a decision, not an error."],
    examples: [
      {
        title: "A validator that accepted extra text",
        code: 'import re\ndef is_code(text):\n    return re.search(r"[A-Z]{2}-\\d+", text) is not None\nprint(is_code("PY-101"))\nprint(is_code("PY-101 extra"))',
        output: 'True\nTrue',
        explanation: "Both calls report True because the pattern appears inside both strings. The second value should have been rejected, so the validator is answering a weaker question than the one its name promises.",
        reasons: [
          "The import makes the regular-expression functions available.",
          "def declares the validator whose name states the whole-value rule.",
          "search looks for the pattern anywhere, so trailing text does not stop a match.",
          "The first value is a valid code and matches, which is correct.",
          "The second value contains a valid code and extra text, and search still reports a match, which is the defect.",
        ],
      },
      {
        title: "Require the whole string to match",
        code: 'import re\ndef is_code(text):\n    return re.fullmatch(r"[A-Z]{2}-\\d+", text) is not None\nprint(is_code("PY-101"))\nprint(is_code("PY-101 extra"))',
        output: 'True\nFalse',
        explanation: "fullmatch anchors the pattern to both ends of the string, so extra text makes the rule fail and the validator returns False. The same two calls now separate the valid value from the invalid one.",
        reasons: [
          "The import is unchanged.",
          "The validator keeps its name and its single responsibility.",
          "fullmatch requires the entire string to be two letters, a hyphen, and digits, which is the stated rule.",
          "The valid code still passes.",
          "The value with extra text now fails, which is the behavior the name promised all along.",
        ],
      },
    ],
    exercise: {
      prompt: "Write is_code(text) that returns True only when text is exactly two uppercase letters, a hyphen, and digits. Print is_code(\"PY-101\") and is_code(\"PY-101 extra\").",
      starterCode: 'import re\n# Require the whole string to match\n',
      solution: 'import re\ndef is_code(text):\n    return re.fullmatch(r"[A-Z]{2}-\\d+", text) is not None\nprint(is_code("PY-101"))\nprint(is_code("PY-101 extra"))',
      solutionExplanation: "re.fullmatch anchors the pattern to the entire string, so the extra text on the second line makes the match fail as the rule requires.",
      testCases: [{ label: "Whole-string match", expected: 'True\nFalse' }],
      hints: ["Use fullmatch rather than search.", "Compare the result with None and return a boolean.", "Include one value that must fail."],
    },
    recap: ["search answers a different question than fullmatch.", "A validator is only proven by the inputs it rejects.", "Returning a boolean keeps the rule usable in a condition."],
    decisionGuide: [
      { use: "fullmatch for whole-value validation", insteadOf: "search plus a length check", reason: "One anchored call states the rule exactly, while a fragment match plus length checks still allows stray characters inside." },
      { use: "testing a value that must fail", insteadOf: "testing only accepted values", reason: "A rule that never saw a rejection has not been tested at all." },
    ],
  },
  // Chapter 7
  7: {
    title: "Debug lab: naming the exception correctly",
    minutes: 33,
    summary: "Repair a handler that catches the wrong exception type for a missing file.",
    learningGoals: ["Read which exception type a failing call actually raised", "Match the except clause to the failure it describes", "Explain why a wrong type lets the error escape"],
    explanation: "An except clause only handles the type it names, so a handler written for ValueError does nothing when the real failure is FileNotFoundError. The program then stops with the original traceback, which is better than hiding the error but is also not the recovery the function promised. Reading the failing line and the exception name is the fastest way to close that gap.",
    keywordNotes: ["except names the types it can handle; anything else keeps travelling up the call stack.", "FileNotFoundError is a subclass of OSError, so catching OSError also catches it.", "A recovery branch should name the failure it recovers from, not a guess."],
    examples: [
      {
        title: "The handler that never ran",
        code: 'from pathlib import Path\ndef load(path):\n    try:\n        return path.read_text(encoding="utf-8")\n    except ValueError:\n        return "missing"\ntry:\n    print(load(Path("absent-note.txt")))\nexcept OSError as error:\n    print(type(error).__name__)',
        output: 'FileNotFoundError',
        explanation: "The read fails with FileNotFoundError, which is not a ValueError, so the function's handler never runs. The outer block catches it only to prove which type was really raised, and that name is the information needed for the repair.",
        reasons: [
          "Path comes from pathlib so the file can be named as an object.",
          "load declares the helper that promises a fallback for a missing file.",
          "try marks the operation that can fail.",
          "read_text raises when the file does not exist, which is the failure this lesson is about.",
          "except ValueError names a type this call never raises, so the handler is dead code.",
          "The intended fallback therefore never returns.",
          "The outer try keeps the example's output to one readable line instead of a traceback.",
          "The call supplies a path that is not on disk, which triggers the failure.",
          "The outer handler catches whatever escaped the function so the example can report it.",
          "The printed name is the evidence the repair starts from: the dead handler had to catch FileNotFoundError.",
        ],
      },
      {
        title: "Catch the failure that actually occurs",
        code: 'from pathlib import Path\ndef load(path):\n    try:\n        return path.read_text(encoding="utf-8")\n    except FileNotFoundError:\n        return "missing"\nprint(load(Path("absent-note.txt")))',
        output: 'missing',
        explanation: "The handler now names the exception the read actually raises, so the fallback runs and the function keeps its promise. Nothing else about the function changed, which is typical for this class of bug.",
        reasons: [
          "The import is unchanged.",
          "The helper keeps its contract: text for a stored file, a fallback for a missing one.",
          "The operation that can fail is still wrapped.",
          "The read call is identical, so the repair is only in the handler.",
          "FileNotFoundError is the name Python reported, which is what makes this handler live code.",
          "The fallback now returns the value the function promised.",
          "The call prints missing, which proves the recovery path ran.",
        ],
      },
    ],
    exercise: {
      prompt: "Write load(path) that returns the file text, or \"missing\" when the file does not exist. Print load(Path(\"absent-note.txt\")).",
      starterCode: 'from pathlib import Path\n# Return a fallback when the file is missing\n',
      solution: 'from pathlib import Path\ndef load(path):\n    try:\n        return path.read_text(encoding="utf-8")\n    except FileNotFoundError:\n        return "missing"\nprint(load(Path("absent-note.txt")))',
      solutionExplanation: "Catching FileNotFoundError is the handler the call can actually reach, so a path that is not on disk returns the documented fallback.",
      testCases: [{ label: "Missing file falls back", expected: 'missing' }],
      hints: ["Read the file inside a try block.", "Name FileNotFoundError in the except clause.", "Return the fallback text from the handler."],
    },
    recap: ["An except clause handles only the types it names.", "The exception's own name is the evidence for choosing the handler.", "A dead handler is invisible until the failure it ignored arrives."],
    decisionGuide: [
      { use: "catching the specific exception", insteadOf: "catching Exception and returning a fallback", reason: "The specific clause keeps unrelated failures visible instead of turning every bug into the same quiet result." },
      { use: "reading the exception name first", insteadOf: "guessing the type from memory", reason: "The traceback states the type, so the handler can match it exactly." },
    ],
  },
  // Chapter 8
  8: {
    title: "Debug lab: an import that only exists inside a function",
    minutes: 34,
    summary: "Repair a NameError caused by a local import the rest of the module cannot see.",
    learningGoals: ["Explain the scope of an import inside a function", "Move shared imports to module level", "Read a NameError as a scope question, not a spelling question"],
    explanation: "An import statement binds a name in the scope where it appears. Inside a function that binding disappears when the call ends, so another function cannot use it. The first function worked, which is exactly why the failure looked mysterious: the module needs the import once, at the top, where every function can read it.",
    keywordNotes: ["An import inside a function creates a name local to that call.", "Module-level imports are visible to every function in the file.", "NameError means the name was not bound in any scope the line can see."],
    examples: [
      {
        title: "The import the second function cannot see",
        code: 'def average(values):\n    import statistics\n    return statistics.mean(values)\ndef summary(values):\n    return statistics.mean(values), len(values)\nprint(average([1, 2, 3]))\ntry:\n    print(summary([1, 2, 3]))\nexcept NameError as error:\n    print(type(error).__name__)',
        output: '2\nNameError',
        explanation: "average works because its own import runs during the call. summary has no such import, and no module-level binding exists, so the name statistics is unknown there and Python raises NameError.",
        reasons: [
          "average declares the first helper.",
          "The import binds statistics only for the duration of this call, which is the hidden cause of the bug.",
          "The mean of the list is returned, so the first helper appears to work perfectly.",
          "summary declares a second helper that also needs the statistics module.",
          "The tuple it builds refers to statistics, and that name is not visible in this scope.",
          "The failure happens at call time rather than at import time, which is why the first helper appeared to work.",
          "The first call prints the average and hides the problem.",
          "The second call is wrapped so the failure can be reported as evidence.",
          "The wrapped call raises NameError.",
          "The except clause prints the exception type, which points at a scope problem rather than a misspelling.",
        ],
      },
      {
        title: "Import once, where every function can see it",
        code: 'import statistics\ndef average(values):\n    return statistics.mean(values)\ndef summary(values):\n    return statistics.mean(values), len(values)\nprint(average([1, 2, 3]))\nprint(summary([1, 2, 3]))',
        output: '2\n(2, 3)',
        explanation: "The import now happens once at module level, so both helpers can use it and no call needs its own copy. The second call returns a tuple of the mean and the count, which is the summary the function promises.",
        reasons: [
          "The import is now a module-level statement, so the name exists for the whole file.",
          "average keeps its body, minus the redundant local import.",
          "The mean is returned exactly as before.",
          "summary keeps its own responsibility.",
          "Both helpers now see statistics, so this line works.",
          "The first call prints the average.",
          "The second call prints the tuple the summary returns, which proves the fix.",
        ],
      },
    ],
    exercise: {
      prompt: "Import statistics at the top of the file. Define average(values) and summary(values) that both use it, then print average([1, 2, 3]) and summary([1, 2, 3]).",
      starterCode: '# Import the module once, at the top\n',
      solution: 'import statistics\ndef average(values):\n    return statistics.mean(values)\ndef summary(values):\n    return statistics.mean(values), len(values)\nprint(average([1, 2, 3]))\nprint(summary([1, 2, 3]))',
      solutionExplanation: "The import sits at module level where both helpers can see it, so the second call returns its tuple instead of raising NameError.",
      testCases: [{ label: "Module import used twice", expected: '2\n(2, 3)' }],
      hints: ["Put the import above the first function.", "Both helpers call statistics.mean.", "The summary returns the mean and the count together."],
    },
    recap: ["An import binds a name in the scope where it appears.", "Shared dependencies belong at module level.", "NameError is a scope question before it is a spelling question."],
    decisionGuide: [
      { use: "a module-level import", insteadOf: "an import inside every function that needs it", reason: "One import makes the dependency visible at the top of the file instead of scattered through the call sites." },
      { use: "reading NameError as scope", insteadOf: "assuming a typo", reason: "The failing name is often correct; what is missing is the binding the line can see." },
    ],
  },
  // Chapter 9
  9: {
    title: "Debug lab: an initializer that forgot self",
    minutes: 32,
    summary: "Repair an AttributeError caused by assigning to a local name instead of the instance.",
    learningGoals: ["Read AttributeError as a missing instance attribute", "Explain what self.minutes = minutes stores", "Check the initializer before the methods that read it"],
    explanation: "Inside a method the local name and the instance attribute are different things. Writing minutes = minutes assigns the parameter to itself and discards the value when the call ends, so the instance never receives the attribute its methods read. The repair is one prefix, and the lesson is to read an initializer as a list of the attributes the object will have.",
    keywordNotes: ["self.minutes = minutes stores the parameter on the instance; minutes = minutes stores nothing new.", "AttributeError from a method usually means the initializer never created the attribute.", "An initializer is the authoritative list of the attributes an object owns."],
    examples: [
      {
        title: "The attribute that was never stored",
        code: 'class Timer:\n    def __init__(self, minutes):\n        minutes = minutes\n    def remaining(self):\n        return self.minutes\ntimer = Timer(25)\ntry:\n    print(timer.remaining())\nexcept AttributeError as error:\n    print(type(error).__name__)',
        output: 'AttributeError',
        explanation: "The initializer assigns the parameter to a local name that happens to be spelled the same, so the instance has no minutes attribute at all. remaining then asks the instance for something that does not exist and Python raises AttributeError.",
        reasons: [
          "class declares the object type this lesson repairs.",
          "The initializer receives the minutes the caller supplied.",
          "Without self, this line assigns the parameter to itself and the instance stays empty.",
          "remaining declares the method that reads the stored value.",
          "The method asks the instance for minutes, which the initializer never created.",
          "Construction succeeds, because nothing here failed yet.",
          "The call to the method is wrapped so the failure can be shown as evidence.",
          "The method raises AttributeError when the attribute is missing.",
          "The handler prints the exception type, which points straight at a missing attribute.",
          "The message names the attribute the initializer never stored, which is where the repair belongs.",
        ],
      },
      {
        title: "Store the value on the instance",
        code: 'class Timer:\n    def __init__(self, minutes):\n        self.minutes = minutes\n    def remaining(self):\n        return self.minutes\nprint(Timer(25).remaining())',
        output: '25',
        explanation: "self.minutes = minutes creates the attribute on the object being constructed, so the method that reads it finds a value. The call now prints the stored minutes.",
        reasons: [
          "The class declaration is unchanged.",
          "The initializer still receives the caller's value.",
          "The assignment now targets the instance, which is the repair.",
          "The method is unchanged and still reads minutes.",
          "The attribute exists, so this lookup succeeds.",
          "The program prints the stored value, 25.",
        ],
      },
    ],
    exercise: {
      prompt: "Define Timer with an initializer that stores minutes on the instance and a remaining() method that returns it. Print Timer(25).remaining().",
      starterCode: 'class Timer:\n    def __init__(self, minutes):\n        # Store the value on the instance\n',
      solution: 'class Timer:\n    def __init__(self, minutes):\n        self.minutes = minutes\n    def remaining(self):\n        return self.minutes\nprint(Timer(25).remaining())',
      solutionExplanation: "Assigning through self stores the value on the instance, so the method reads the minutes the caller supplied.",
      testCases: [{ label: "Stored attribute", expected: '25' }],
      hints: ["Assign to self.minutes.", "The method returns self.minutes.", "Construct with 25 and call the method."],
    },
    recap: ["A parameter and an instance attribute are different names.", "The initializer decides which attributes the object will have.", "AttributeError at a method call often starts in the initializer."],
    decisionGuide: [
      { use: "assigning through self in the initializer", insteadOf: "a local assignment that repeats the parameter name", reason: "The instance is the object that outlives the call, so only the self-prefixed assignment persists." },
      { use: "reading the initializer first", insteadOf: "searching every method for the bug", reason: "The missing attribute is created, or not created, in exactly one place." },
    ],
  },
  // Chapter 11
  11: {
    title: "Debug lab: removing from a list while iterating",
    minutes: 35,
    summary: "Repair a filter that silently skipped an element and left invalid data behind.",
    learningGoals: ["Explain why removal during iteration shifts the elements the loop has not seen", "Filter into a new list instead of mutating in place", "Spot a silent bug that raises no exception"],
    explanation: "A list loop advances by position, so removing the element at the current position pulls the next element back into a slot the loop has already passed. Nothing is raised: the program simply returns data that still breaks the rule. The repair builds the kept values in a new list, which removes the interaction between reading and writing.",
    keywordNotes: ["Removing an item during a list loop shifts every later element one position to the left.", "A comprehension that builds a new list has no such interaction.", "Silent bugs are the ones that need a test on the result, because no exception will point at them."],
    examples: [
      {
        title: "A filter that skipped one value",
        code: 'scores = [3, -1, -2, 4, 5]\nfor score in scores:\n    if score < 0:\n        scores.remove(score)\nprint(scores)',
        output: '[3, -2, 4, 5]',
        explanation: "After -1 is removed, the loop's next position holds 4 because -2 moved into the slot it had already passed, so -2 is never examined and survives. The program prints a list that still contains the value the requirement said to remove.",
        reasons: [
          "The list contains two invalid values in adjacent positions, which is what exposes the defect.",
          "The loop walks the list by position while the body is allowed to change it.",
          "The rule marks the values that must not survive.",
          "remove takes the current value out and shifts everything after it one slot to the left.",
          "The loop advances past the value that moved into the current position, so print shows a list that still holds -2 without raising any error.",
        ],
      },
      {
        title: "Build the kept values in a new list",
        code: 'scores = [3, -1, -2, 4, 5]\nkept = [score for score in scores if score >= 0]\nprint(kept)',
        output: '[3, 4, 5]',
        explanation: "The comprehension reads the original list once and writes the accepted values somewhere else, so nothing shifts and no element is skipped. The result states the rule positively: keep the scores that are not negative.",
        reasons: [
          "The same input is used, so the repair is visible in the output alone.",
          "The comprehension builds a new list from the values that satisfy the positive form of the rule.",
          "print shows the filtered list, which now contains no invalid values.",
        ],
      },
    ],
    exercise: {
      prompt: "From scores = [3, -1, -2, 4, 5], keep only the values that are not negative and print the result.",
      starterCode: 'scores = [3, -1, -2, 4, 5]\n# Keep the valid scores without changing the list while reading it\n',
      solution: 'scores = [3, -1, -2, 4, 5]\nkept = [score for score in scores if score >= 0]\nprint(kept)',
      solutionExplanation: "Building a new list from a comprehension reads the original once, so no value is skipped and no element moves under the loop.",
      testCases: [{ label: "Filtering without skipping", expected: '[3, 4, 5]' }],
      hints: ["State the rule positively.", "Build a new list with a comprehension.", "Print the new list."],
    },
    recap: ["List removal during iteration shifts the elements still to be visited.", "A new list avoids the read-write interaction entirely.", "A wrong result without an exception needs a test on the value."],
    decisionGuide: [
      { use: "filtering into a new list", insteadOf: "removing from the list being iterated", reason: "The new list cannot skip an element, because the original is never changed." },
      { use: "testing the resulting value", insteadOf: "waiting for an exception", reason: "This defect raises nothing, so only the result tells you the rule was broken." },
    ],
  },
  // Chapter 12
  12: {
    title: "Debug lab: a key that cannot be hashed",
    minutes: 32,
    summary: "Repair a TypeError by storing a tuple key instead of a list.",
    learningGoals: ["Read TypeError as a hashability problem", "Choose an immutable key type", "Explain what makes a dictionary key usable"],
    explanation: "A dictionary key must be hashable, which means its value cannot change after it is stored. A list is mutable and therefore rejected, and Python raises TypeError before the dictionary is touched. The repair uses a tuple, which holds the same two values and can never change.",
    keywordNotes: ["Dictionary keys must be hashable, so lists and dictionaries cannot be keys.", "A tuple holds ordered values and is immutable when its contents are.", "TypeError on an assignment to a key points at the key's type, not at the value's."],
    examples: [
      {
        title: "A list used as a dictionary key",
        code: 'cache = {}\nkey = ["python", 101]\ntry:\n    cache[key] = "found"\nexcept TypeError as error:\n    print(type(error).__name__)\nprint(len(cache))',
        output: 'TypeError\n0',
        explanation: "The list cannot be hashed, so the assignment fails before anything is stored and the cache is still empty. Printing the length afterwards shows that the operation had no partial effect.",
        reasons: [
          "The empty dictionary is the store this example writes into.",
          "The key is a list, which is mutable and therefore unhashable.",
          "try marks the operation that will fail.",
          "Assigning with that key raises TypeError before the dictionary changes.",
          "The handler names the failure Python raised.",
          "The handler prints the exception type as evidence.",
          "The length is printed to show the failed assignment stored nothing.",
        ],
      },
      {
        title: "An immutable tuple key",
        code: 'cache = {}\nkey = ("python", 101)\ncache[key] = "found"\nprint(cache[key])',
        output: 'found',
        explanation: "The tuple holds the same two values and never changes, so it is hashable and can be used as a key. The lookup afterwards returns the stored value, which proves the write and the read agree.",
        reasons: [
          "The dict is declared exactly as before.",
          "The key is now a tuple, which is the repair.",
          "The assignment succeeds because the key can be hashed.",
          "The same key retrieves the stored value, and print shows found.",
        ],
      },
    ],
    exercise: {
      prompt: "Create cache = {}, store \"found\" under the key (\"python\", 101), and print the stored value.",
      starterCode: 'cache = {}\n# Use an immutable key\n',
      solution: 'cache = {}\nkey = ("python", 101)\ncache[key] = "found"\nprint(cache[key])',
      solutionExplanation: "A tuple is hashable and describes the pair, so the same names find the stored record instead of raising TypeError.",
      testCases: [{ label: "Lookup with a tuple key", expected: 'found' }],
      hints: ["Use parentheses for the key.", "Assign with the key inside square brackets.", "Read the value back with the same key."],
    },
    recap: ["Dictionary keys must be hashable, which rules out lists.", "A tuple carries the same values with an immutable type.", "Reading the value back proves the key worked."],
    decisionGuide: [
      { use: "a tuple key", insteadOf: "a list key plus a string conversion", reason: "The tuple keeps the structure of the key without inventing a text format to work around the TypeError." },
      { use: "reading the value back after a write", insteadOf: "checking only that no error was raised", reason: "The read confirms the key is stable enough to find the entry again." },
    ],
  },
  // Chapter 13
  13: {
    title: "Debug lab: a generator that was already consumed",
    minutes: 34,
    summary: "Repair an empty second result caused by reusing a spent iterator.",
    learningGoals: ["Explain why an iterator yields each value once", "Choose between materialising a result and calling the factory again", "Read an empty list as an exhausted iterator, not a broken pipeline"],
    explanation: "A generator produces its values once and then remembers that it is finished. Assigning one to a name stores the iterator, not the data, so the second pass has nothing left to give. Calling the generator function again creates a fresh iterator, which is the repair when the caller needs the sequence twice.",
    keywordNotes: ["An iterator is consumed as it is read; a second pass over the same object yields nothing.", "Calling the generator function again returns a new iterator.", "list() over a generator records the values so they can be read more than once."],
    examples: [
      {
        title: "The second pass that found nothing",
        code: 'values = (value * 2 for value in range(4))\nfirst = list(values)\nsecond = list(values)\nprint(first)\nprint(second)',
        output: '[0, 2, 4, 6]\n[]',
        explanation: "The generator expression created one iterator. The first list() drained it, and the second had nothing left, so the program printed a correct result followed by an empty one. Nothing raised, which is why the bug must be read from the code or caught by a second assertion.",
        reasons: [
          "The parentheses create a generator, which is an iterator rather than a stored list.",
          "list() reads the iterator from start to finish, producing the four values.",
          "The iterator is now exhausted, and this line creates the variable that shows it.",
          "The first result is printed and looks correct.",
          "The second result is empty, which is the symptom of a spent iterator rather than a wrong rule.",
        ],
      },
      {
        title: "Ask the factory for a fresh iterator",
        code: 'def doubled(limit):\n    return (value * 2 for value in range(limit))\nprint(list(doubled(4)))\nprint(list(doubled(4)))',
        output: '[0, 2, 4, 6]\n[0, 2, 4, 6]',
        explanation: "Each call to doubled builds a new generator, so both prints read a complete sequence. The rule stays lazy, because nothing is materialised until list() asks for the values.",
        reasons: [
          "def declares a factory whose job is to produce a fresh iterator per call.",
          "The generator expression is created when the function is called, not when it is defined.",
          "The first call prints a full sequence.",
          "The second call builds its own generator and prints the same sequence, which is the repair.",
        ],
      },
    ],
    exercise: {
      prompt: "Define doubled(limit) returning a generator of doubled values, then print list(doubled(4)) twice.",
      starterCode: '# Return a fresh generator from a function\n',
      solution: 'def doubled(limit):\n    return (value * 2 for value in range(limit))\nprint(list(doubled(4)))\nprint(list(doubled(4)))',
      solutionExplanation: "Each call creates a fresh generator, so the second pass produces the same sequence rather than an exhausted one.",
      testCases: [{ label: "Two independent passes", expected: '[0, 2, 4, 6]\n[0, 2, 4, 6]' }],
      hints: ["Return a generator expression from the function.", "Call the function once per print.", "Wrap each call in list()."],
    },
    recap: ["An iterator yields its values once.", "A factory function produces a new iterator per call.", "An empty second result is a consumption problem before it is a logic problem."],
    decisionGuide: [
      { use: "calling the generator function again", insteadOf: "reusing the same iterator object", reason: "A fresh call rebuilds the sequence, while the spent object can never produce values again." },
      { use: "materialising with list() when the data is needed twice", insteadOf: "keeping a lazy iterator and hoping", reason: "list() records the values so a later reader is not surprised by an empty result." },
    ],
  },
  // Chapter 15
  15: {
    title: "Debug lab: an annotation that was never enforced",
    minutes: 33,
    summary: "Repair a function that trusted a type hint and multiplied text instead of numbers.",
    learningGoals: ["Explain that annotations are documentation at runtime", "Validate a value at the function boundary", "Trace the wrong output back to an unmet input assumption"],
    explanation: "Annotations are read by tools and people, and Python does not act on them when the function runs. A caller that passes the wrong type therefore gets whatever the operator does with that type, which is how doubling a string produced 33. The repair states the assumption as code: check the type, raise a named error, and keep the calculation for the values the function accepts.",
    keywordNotes: ["Annotations describe intent; they do not convert or reject values at runtime.", "isinstance checks the type of a value during the call.", "A boundary that raises a named error turns a silent wrong answer into a diagnosis."],
    examples: [
      {
        title: "Doubling text instead of numbers",
        code: 'def double(value: int) -> int:\n    return value * 2\nprint(double("3"))',
        output: '33',
        explanation: "The annotation says int, but nothing checks it. The multiplication operator repeats a string, so the call returns '33', which is a plausible-looking answer that no test of the intended rule would accept.",
        reasons: [
          "def declares the parameter and the return type as documentation, not as a runtime check.",
          "The multiplication assumes a number, and the string operand changes its meaning without any error.",
          "The call passes text, and the printed result 33 shows the wrong kind of value passed silently.",
        ],
      },
      {
        title: "Check the value at the boundary",
        code: 'def double(value: int) -> int:\n    if not isinstance(value, int):\n        raise TypeError("value must be int")\n    return value * 2\nprint(double(3))',
        output: '6',
        explanation: "The guard runs before the calculation, so a wrong type stops at a name the caller can read instead of producing plausible nonsense. The same annotation stays, now backed by code.",
        reasons: [
          "The annotation still documents the intended type.",
          "The guard asks whether the received value really is an int.",
          "A named TypeError tells the caller exactly what the boundary expects.",
          "The calculation now runs on a value the function can trust.",
          "The valid call prints 6, and a wrong type would raise instead of printing.",
        ],
      },
    ],
    exercise: {
      prompt: "Write double(value: int) -> int that raises TypeError when value is not an int and otherwise returns value * 2. Print double(3).",
      starterCode: 'def double(value: int) -> int:\n    # Reject a value the rule cannot use\n',
      solution: 'def double(value: int) -> int:\n    if not isinstance(value, int):\n        raise TypeError("value must be int")\n    return value * 2\nprint(double(3))',
      solutionExplanation: "The isinstance guard converts the annotated contract into a runtime check, so the int input is rejected with a clear ValueError instead of producing a wrong total.",
      testCases: [{ label: "Typed boundary", expected: '6' }],
      hints: ["Use isinstance for the check.", "Raise TypeError with a short message.", "Return the doubled value after the guard."],
    },
    recap: ["Annotations do not enforce types at runtime.", "A boundary check replaces a silent wrong answer with a named error.", "The annotation and the guard together describe and enforce the same contract."],
    decisionGuide: [
      { use: "an isinstance check at the boundary", insteadOf: "trusting the annotation", reason: "Only the runtime check can reject the value before the wrong operation runs." },
      { use: "raising a named error", insteadOf: "returning None for a bad type", reason: "An error states the contract failure, while None makes the caller guess what went wrong." },
    ],
  },
  // Chapter 16
  16: {
    title: "Debug lab: a URL built by joining text",
    minutes: 32,
    summary: "Repair a query string that broke because a space was pasted into it.",
    learningGoals: ["Explain why text concatenation is the wrong tool for a query string", "Encode parameters with urlencode", "Read a URL as data with a syntax, not as a sentence"],
    explanation: "A query string has its own syntax: certain characters separate parameters and certain characters are not allowed inside a value. Concatenation ignores both rules, so a topic containing a space produces a URL that means something different from what the code intended. urlencode applies the rules for you and keeps the parameter visible in the code.",
    keywordNotes: ["A space inside a query value must be percent- or plus-encoded before it can travel in a URL.", "urlencode takes a mapping and returns a correctly escaped query string.", "Concatenating user text into a URL is the same class of mistake as concatenating it into SQL."],
    examples: [
      {
        title: "A URL that broke on one space",
        code: 'topic = "python basics"\nurl = "/lessons?topic=" + topic\nprint(url)',
        output: '/lessons?topic=python basics',
        explanation: "The concatenation produced text that looks like a URL and is not one: the space inside the value is unescaped, so anything that parses this string will stop the parameter at the space or reject it entirely.",
        reasons: [
          "The topic holds a value with a space, which is exactly what this bug needs to appear.",
          "Text concatenation copies the space into the query string unchanged, because the string is treated as plain text.",
          "print shows the broken URL, and the space is the visible symptom.",
        ],
      },
      {
        title: "Encode the parameter",
        code: 'from urllib.parse import urlencode\nurl = "/lessons?" + urlencode({"topic": "python basics"})\nprint(url)',
        output: '/lessons?topic=python+basics',
        explanation: "urlencode escapes the value according to the URL rules, so the space becomes part of the encoded value rather than a separator. The parameter now travels intact.",
        reasons: [
          "The import brings in the standard encoder instead of hand-written escaping.",
          "urlencode turns the mapping into a query string, replacing the space with its encoded form.",
          "The printed URL is now valid, and the topic survives as one value.",
        ],
      },
    ],
    exercise: {
      prompt: "Import urlencode. Build \"/lessons?\" with a topic parameter for \"python basics\" and print it.",
      starterCode: 'from urllib.parse import urlencode\n# Encode the parameter before it reaches the URL\n',
      solution: 'from urllib.parse import urlencode\nurl = "/lessons?" + urlencode({"topic": "python basics"})\nprint(url)',
      solutionExplanation: "urlencode escapes the space, so the topic travels as one intact parameter value.",
      testCases: [{ label: "Encoded query value", expected: '/lessons?topic=python+basics' }],
      hints: ["Pass a dictionary to urlencode.", "Join the encoded query to the path with +.", "Print the finished URL."],
    },
    recap: ["A URL is structured data, so values inside it must be encoded.", "urlencode applies the escaping rules the URL grammar requires.", "A legal-looking string can still be an invalid URL."],
    decisionGuide: [
      { use: "urlencode for query values", insteadOf: "concatenating the value into the query", reason: "The encoder handles every reserved character, while concatenation handles none of them." },
      { use: "treating a URL as data", insteadOf: "treating a URL as a sentence", reason: "Structure explains which characters separate parameters and which must travel inside a value." },
    ],
  },
  // Chapter 17
  17: {
    title: "Debug lab: a value pasted into SQL text",
    minutes: 34,
    summary: "Repair a database write that failed on an apostrophe by binding the value instead.",
    learningGoals: ["Read an OperationalError as a syntax failure in the generated statement", "Bind parameters instead of building SQL text", "Explain why a successful test value hides the defect"],
    explanation: "SQL text and data are different things. Joining a value into the statement lets that value change the statement's syntax, which is why the apostrophe in O'Brien ended the string early. Binding passes the value separately, so the database sees the statement and the data as distinct, and no value can rewrite the command.",
    keywordNotes: ["A parameter placeholder keeps data out of the statement's syntax.", "The printed name, OperationalError, is the database reporting a statement it could not parse.", "A value with a quote is the smallest test that exposes text-built SQL."],
    examples: [
      {
        title: "The write that failed on an apostrophe",
        code: 'import sqlite3\nconnection = sqlite3.connect(":memory:")\nconnection.execute("CREATE TABLE learner (name TEXT)")\ntitle = "O\'Brien"\ntry:\n    connection.execute("INSERT INTO learner VALUES (\'" + title + "\')")\nexcept sqlite3.Error as error:\n    print(type(error).__name__)',
        output: 'OperationalError',
        explanation: "The apostrophe in the name closed the string literal inside the generated statement, so the database received text that is not valid SQL and reported it. The program never stored the row, and the cause is the string concatenation two lines earlier.",
        reasons: [
          "sqlite3 provides the in-memory database this example uses.",
          "The connection is created in memory, so the example needs no file.",
          "The table declares one text column for the names.",
          "The name contains an apostrophe, which is the value that exposes the defect.",
          "try marks the write so the failure can be reported rather than crashing the example.",
          "The value is joined into the statement, so its apostrophe becomes part of the SQL syntax.",
          "sqlite3 raises OperationalError because the statement it received cannot be parsed.",
          "The handler prints the error type as evidence of a syntax failure rather than a missing table.",
        ],
      },
      {
        title: "Bind the value to the statement",
        code: 'import sqlite3\nconnection = sqlite3.connect(":memory:")\nconnection.execute("CREATE TABLE learner (name TEXT)")\ntitle = "O\'Brien"\nconnection.execute("INSERT INTO learner VALUES (?)", (title,))\nprint(connection.execute("SELECT COUNT(*) FROM learner").fetchone()[0])',
        output: '1',
        explanation: "The placeholder marks where a value goes, and the tuple carries the value itself, so the apostrophe is data and can never change the statement. The count afterwards proves the row was stored.",
        reasons: [
          "The import is unchanged.",
          "The in-memory connection is created the same way.",
          "The table declaration is identical.",
          "The same value with the apostrophe is used, which shows the repair is in the call, not the data.",
          "The statement now contains a placeholder and the value travels beside it.",
          "The count is read back and printed, confirming the insert succeeded.",
        ],
      },
    ],
    exercise: {
      prompt: "Create an in-memory learner table, insert the name O'Brien with a bound parameter, and print the row count.",
      starterCode: 'import sqlite3\n# Bind the value instead of joining it into the statement\n',
      solution: 'import sqlite3\nconnection = sqlite3.connect(":memory:")\nconnection.execute("CREATE TABLE learner (name TEXT)")\nconnection.execute("INSERT INTO learner VALUES (?)", ("O\'Brien",))\nprint(connection.execute("SELECT COUNT(*) FROM learner").fetchone()[0])',
      solutionExplanation: "The placeholder keeps the apostrophe inside the data, so the insert succeeds and the row count proves it.",
      testCases: [{ label: "Bound parameter", expected: '1' }],
      hints: ["Use a ? placeholder in the statement.", "Pass the value as a one-item tuple.", "Read COUNT(*) to prove the row exists."],
    },
    recap: ["Data joined into SQL text can change the statement's meaning.", "Placeholders separate the command from its values.", "A value with a quote is the smallest honest test for this bug."],
    decisionGuide: [
      { use: "bound parameters", insteadOf: "string concatenation into the statement", reason: "Binding makes the value unable to alter the syntax, whatever characters it contains." },
      { use: "testing with a quote in the data", insteadOf: "testing with a plain name", reason: "Plain values usually work in both versions, so only an awkward value tells the two apart." },
    ],
  },
  // Chapter 18
  18: {
    title: "Debug lab: a coroutine that was never awaited",
    minutes: 33,
    summary: "Repair a monitor that returned a coroutine object instead of a result.",
    learningGoals: ["Recognise a coroutine object in output", "Add the await that runs the coroutine", "Explain what asyncio.run does with the outermost coroutine"],
    explanation: "Calling an async function does not run it: it builds a coroutine object that someone must await. A missing await is therefore silent at the point of the call and visible only in the value that reaches the print. The repair adds the keyword that asks the event loop to run the work and hand back the result.",
    keywordNotes: ["Calling an async function returns a coroutine object rather than a value.", "await suspends the current coroutine until the awaited one finishes.", "asyncio.run drives the outermost coroutine to completion."],
    examples: [
      {
        title: "A result that was only a promise",
        code: 'import asyncio\nasync def check(name):\n    return name + ": ok"\nasync def monitor():\n    result = check("api")\n    return result\nvalue = asyncio.run(monitor())\nprint(type(value).__name__)',
        output: 'coroutine',
        explanation: "The inner call created a coroutine object and returned it, so monitor handed a description of work to the caller instead of a result. Nothing failed, and the printed type is the clue: the value is a coroutine, not the string the function appears to return.",
        reasons: [
          "asyncio supplies the runner and the awaitable objects.",
          "check declares a coroutine that produces one string.",
          "Returning a value from a coroutine is what makes it awaitable work.",
          "monitor declares the coroutine that should collect the result.",
          "The call builds a coroutine object; without await, no work happens here.",
          "That object is returned, so monitor's own result is a promise rather than the text.",
          "asyncio.run drives monitor and returns what it produced.",
          "The printed type, coroutine, is the evidence that the await is missing.",
        ],
      },
      {
        title: "Await the call",
        code: 'import asyncio\nasync def check(name):\n    return name + ": ok"\nasync def monitor():\n    return await check("api")\nprint(asyncio.run(monitor()))',
        output: 'api: ok',
        explanation: "await runs the inner coroutine and resumes monitor with its result, so the outer coroutine produces the string rather than a promise. asyncio.run then returns that string to ordinary code.",
        reasons: [
          "The import is unchanged.",
          "The inner coroutine keeps its job.",
          "It still returns one string.",
          "monitor still collects the result, this time with await in front of the call.",
          "The awaited call completes and its value becomes monitor's return value.",
          "The runner executes monitor and print displays the final string.",
        ],
      },
    ],
    exercise: {
      prompt: "Define async check(name) returning name + \": ok\" and async monitor() that awaits it. Print asyncio.run(monitor()).",
      starterCode: 'import asyncio\n# Await the work inside the coroutine\n',
      solution: 'import asyncio\nasync def check(name):\n    return name + ": ok"\nasync def monitor():\n    return await check("api")\nprint(asyncio.run(monitor()))',
      solutionExplanation: "await runs the inner coroutine, so monitor returns the string the caller can format instead of a coroutine object.",
      testCases: [{ label: "Awaited result", expected: 'api: ok' }],
      hints: ["Mark both functions async.", "Put await before the call to check.", "Drive the outer coroutine with asyncio.run."],
    },
    recap: ["An async call returns a coroutine object, not a value.", "await is what runs it and produces the result.", "asyncio.run drives the outermost coroutine."],
    decisionGuide: [
      { use: "await on every awaited call", insteadOf: "calling the coroutine and returning it", reason: "The missing keyword produces a value of the wrong type that no arithmetic or formatting can use." },
      { use: "printing the value's type when output looks wrong", insteadOf: "assuming the function returned wrong data", reason: "The type shows that no work ran at all, which points at the call site rather than the logic." },
    ],
  },
  // Chapter 19
  19: {
    title: "Debug lab: a cache that ignored a changed setting",
    minutes: 36,
    summary: "Repair a cached function whose result depended on a value outside its arguments.",
    learningGoals: ["Explain what a cache key is made of", "Move the dependency into the function's arguments", "Recognise a stale value as a caching defect"],
    explanation: "A cache returns a stored result when the same arguments arrive again, so the result must depend on nothing but those arguments. A function that also reads a module-level value breaks that rule: after the setting changes, the cached entry is still keyed on the old call and returns the old answer. Passing the dependency as an argument repairs the key.",
    keywordNotes: ["A cache key is built from the arguments, so every input the result depends on belongs in them.", "lru_cache stores the first result and reuses it for identical arguments.", "A stale cached value looks like a logic error but is a purity problem."],
    examples: [
      {
        title: "The cached answer that would not change",
        code: 'from functools import lru_cache\nrate = 2\n@lru_cache\ndef convert(value):\n    return value * rate\nprint(convert(3))\nrate = 10\nprint(convert(3))',
        output: '6\n6',
        explanation: "The second call passes the same argument, so the cache returns the stored 6 and never runs the body again, even though rate is now 10. The program is behaving exactly as designed; the design made the result depend on something the key cannot see.",
        reasons: [
          "The import brings the caching decorator in.",
          "rate is a module-level value the function reads but does not receive.",
          "The decorator records results per set of arguments.",
          "convert has one argument, so the key is only the value 3.",
          "The multiplication reads rate from the surrounding scope, which is the hidden dependency.",
          "The first call stores 6 under the key 3.",
          "The setting changes, and nothing tells the cache about it.",
          "The second call with the same key returns the stored 6, which is why the output repeats.",
        ],
      },
      {
        title: "Pass the dependency as an argument",
        code: 'from functools import lru_cache\n@lru_cache\ndef convert(value, rate):\n    return value * rate\nprint(convert(3, 2))\nprint(convert(3, 10))',
        output: '6\n30',
        explanation: "rate is now part of the call, so the two calls have different keys and each result is stored separately. The cache still helps when the same pair arrives twice, and it can no longer return an answer that belongs to another setting.",
        reasons: [
          "The import is unchanged.",
          "The decorator still records results for repeated calls.",
          "convert now receives both values the result depends on, which is the repair.",
          "The multiplication uses only its own arguments.",
          "The first call stores 6 under the key (3, 2).",
          "The second call has a different key, so the body runs and prints 30.",
        ],
      },
    ],
    exercise: {
      prompt: "Use lru_cache on convert(value, rate) that returns value * rate, then print convert(3, 2) and convert(3, 10).",
      starterCode: 'from functools import lru_cache\n# Make every dependency part of the call\n',
      solution: 'from functools import lru_cache\n@lru_cache\ndef convert(value, rate):\n    return value * rate\nprint(convert(3, 2))\nprint(convert(3, 10))',
      solutionExplanation: "Making rate an argument puts it in the cache key, so each setting gets its own stored answer.",
      testCases: [{ label: "Cache keyed on both inputs", expected: '6\n30' }],
      hints: ["Decorate the function with lru_cache.", "Give it two parameters.", "Call it with both values."],
    },
    recap: ["A cached result may depend on nothing outside the arguments that key it.", "Moving the dependency into the call repairs the key.", "A stale value is a purity problem before it is a logic problem."],
    decisionGuide: [
      { use: "passing the dependency to the function", insteadOf: "reading it from the surrounding scope", reason: "Only the argument can be part of the key, so only an argument can keep the cached answer correct." },
      { use: "caching pure functions", insteadOf: "caching functions that read changing state", reason: "A pure function's output is reproducible; anything else can be remembered with the wrong answer." },
    ],
  },
  // Chapter 20
  20: {
    title: "Debug lab: escaping that handled one character",
    minutes: 32,
    summary: "Repair a hand-written escape that left quotes and brackets unescaped.",
    learningGoals: ["Explain what a complete escape has to cover", "Use the escape function from the html module instead of manual replacements", "Recognise partial escaping as a security bug"],
    explanation: "Escaping is a rule about every character that has meaning in the target syntax. Replacing one character leaves the rest intact, so the output still contains quotes and closing brackets that a parser will treat as markup. the escape function imported from the html module applies the whole rule, and the difference is visible in a single print.",
    keywordNotes: ["The escape function from the html module converts the characters that carry meaning in HTML, including <, >, &, and quotes.", "Partial escaping is worse than none, because it looks deliberate and passes a casual review.", "The safe function belongs at the boundary where text becomes markup."],
    examples: [
      {
        title: "Only one character escaped",
        code: 'def safe(text):\n    return text.replace("<", "&lt;")\nprint(safe(\'<a href="x">go</a>\'))',
        output: '&lt;a href="x">go&lt;/a>',
        explanation: "The opening brackets are escaped and the rest of the markup is untouched: the attribute quotes and the closing brackets still arrive as syntax. A browser would parse this text as a link, which is precisely what the function was written to prevent.",
        reasons: [
          "safe declares the helper whose name promises escaped text.",
          "One replacement handles a single character and leaves every other meaningful character as it was.",
          "The printed result shows the mixed output: escaped openings and live quotes and brackets.",
        ],
      },
      {
        title: "Escape the whole rule",
        code: 'from html import escape\nprint(escape(\'<a href="x">go</a>\'))',
        output: '&lt;a href=&quot;x&quot;&gt;go&lt;/a&gt;',
        explanation: "The standard helper escapes every character that carries meaning in HTML, so nothing in the string can be read as markup. The same input now produces text that a browser will display literally.",
        reasons: [
          "The import brings in the standard escaping helper.",
          "escape applies the complete rule in one call, and print shows every meaningful character encoded.",
        ],
      },
    ],
    exercise: {
      prompt: "Import escape from html and print the escaped form of '<a href=\"x\">go</a>'.",
      starterCode: 'from html import escape\n# Escape every meaningful character\n',
      solution: 'from html import escape\nprint(escape(\'<a href="x">go</a>\'))',
      solutionExplanation: "The imported escape function applies the whole HTML rule, so quotes and brackets arrive as text rather than markup.",
      testCases: [{ label: "Complete escaping", expected: '&lt;a href=&quot;x&quot;&gt;go&lt;/a&gt;' }],
      hints: ["Import escape from html.", "Pass the whole string to it once.", "Print the result."],
    },
    recap: ["An escape is a complete rule, not a list of favourite characters.", "The escape function from the html module implements that rule for HTML text.", "Partial escaping passes review while leaving the door open."],
    decisionGuide: [
      { use: "escape from the html module", insteadOf: "replace calls for one or two characters", reason: "The library call covers the whole rule and stays correct if the rule is refined." },
      { use: "escaping at the boundary", insteadOf: "escaping scattered through the code", reason: "One boundary is reviewable; scattered calls are easy to miss." },
    ],
  },
  // Chapter 21
  21: {
    title: "Debug lab: reading an option that was never declared",
    minutes: 32,
    summary: "Repair an AttributeError caused by an argument the parser does not define.",
    learningGoals: ["Read AttributeError on a namespace as a declaration problem", "Declare the option the code reads", "Give the option a default so the common call stays short"],
    explanation: "argparse builds a namespace with exactly the options that were declared. Reading anything else raises AttributeError, and the fix belongs in the declaration rather than in a defensive check at the use site. A default keeps the short call working, which is what the option is for.",
    keywordNotes: ["The parsed namespace contains one attribute per declared argument.", "AttributeError at a use site usually means the parser never declared that name.", "A default lets the usual invocation omit the option entirely."],
    examples: [
      {
        title: "An option the parser never heard of",
        code: 'import argparse\nparser = argparse.ArgumentParser()\nparser.add_argument("--topic")\nargs = parser.parse_args([])\ntry:\n    print(args.mode)\nexcept AttributeError as error:\n    print(type(error).__name__)',
        output: 'AttributeError',
        explanation: "Only --topic was declared, so the namespace has a topic attribute and no mode. The call with an empty argument list parses fine and then fails at the line that reads the missing name.",
        reasons: [
          "argparse is the standard command-line parser.",
          "The parser is created with no options yet.",
          "One option is declared, and it is not the one the next lines read.",
          "An empty argument list is parsed so the example needs no real command line.",
          "The code reads mode, which no declaration created, so the attribute lookup fails.",
          "The handler catches the AttributeError.",
          "The printed type points at the declaration as the place to repair.",
          "The message also names the attribute, which confirms the namespace never contained it.",
        ],
      },
      {
        title: "Declare the option with a default",
        code: 'import argparse\nparser = argparse.ArgumentParser()\nparser.add_argument("--mode", default="study")\nargs = parser.parse_args([])\nprint(args.mode)',
        output: 'study',
        explanation: "The option now exists in the namespace, and the default means the empty argument list still produces a value. The same print statement reads a name the parser actually created.",
        reasons: [
          "The import is unchanged.",
          "The parser is still built the same way.",
          "The declaration now matches the name the program reads and supplies the documented default.",
          "The empty argument list is parsed as before.",
          "The attribute exists, so print displays study.",
        ],
      },
    ],
    exercise: {
      prompt: "Declare --mode with default \"study\", parse an empty argument list, and print the mode.",
      starterCode: 'import argparse\n# Declare the option the program reads\n',
      solution: 'import argparse\nparser = argparse.ArgumentParser()\nparser.add_argument("--mode", default="study")\nargs = parser.parse_args([])\nprint(args.mode)',
      solutionExplanation: "Declaring --mode with a default creates the attribute the program reads, so the empty argument list still produces a value.",
      testCases: [{ label: "Declared option default", expected: 'study' }],
      hints: ["Pass the option name to add_argument.", "Add the default keyword.", "Parse [] so no real arguments are needed."],
    },
    recap: ["The namespace holds only what the parser declared.", "The declaration is the right place to repair a missing attribute.", "A default keeps the common invocation short."],
    decisionGuide: [
      { use: "declaring the option with a default", insteadOf: "a getattr fallback at the use site", reason: "The declaration documents the option and makes it appear in help output, while a fallback hides the missing declaration." },
      { use: "parsing an empty list in a test", insteadOf: "depending on the developer's shell", reason: "An explicit argument list makes the example reproducible." },
    ],
  },
  // Chapter 22
  22: {
    title: "Debug lab: markup built before validation",
    minutes: 35,
    summary: "Repair a renderer that placed untrusted text straight into HTML.",
    learningGoals: ["Explain why building markup before validating is unsafe", "Escape the value before it becomes markup", "Return a status with the body so failures are explicit"],
    explanation: "Once text is placed between markup tags, anything it contains is interpreted as markup. Escaping afterwards is too late, because the value and the tags have already merged into one string. The repair validates first, escapes the value, and only then builds the response, so the status and the rendered text are decided in a deliberate order.",
    keywordNotes: ["Escaping after concatenation cannot help: the parser sees the merged string.", "A route returns a status and a body together so callers can distinguish success from rejection.", "The escape function from the html module keeps the value as text inside the generated markup."],
    examples: [
      {
        title: "Untrusted text inside markup",
        code: 'def render(title):\n    return "<h1>" + title + "</h1>"\nprint(render("<script>alert(1)</script>"))',
        output: '<h1><script>alert(1)</script></h1>',
        explanation: "The value was joined to the tags without escaping, so the printed string contains a live script element inside a heading. The function returns exactly what it was asked for, and that is the problem.",
        reasons: [
          "render declares the helper whose job is a heading.",
          "The concatenation places the caller's text directly between the tags, so its characters become markup.",
          "print shows a heading that contains an executable element rather than text.",
        ],
      },
      {
        title: "Validate, escape, then build",
        code: 'from html import escape\ndef render(title):\n    if not title.strip():\n        return 400, ""\n    return 200, "<h1>" + escape(title) + "</h1>"\nprint(render("<script>alert(1)</script>")[1])',
        output: '<h1>&lt;script&gt;alert(1)&lt;/script&gt;</h1>',
        explanation: "The blank check decides the status, escape turns the value into text, and only then are the tags added. The printed body now shows the input as characters inside a heading instead of an element.",
        reasons: [
          "The import brings in the escaping helper.",
          "The renderer keeps its single responsibility: one heading for one title.",
          "The validation branch rejects empty input before any markup exists.",
          "A rejected request returns a status and an empty body, which the caller can read.",
          "A valid request escapes the value first and then wraps it in tags.",
          "The body is selected from the tuple and printed, which is the repaired output.",
        ],
      },
    ],
    exercise: {
      prompt: "Write render(title) that returns (400, \"\") for a blank title and otherwise (200, escaped heading). Print the body for \"<script>alert(1)</script>\".",
      starterCode: 'from html import escape\n# Validate first, escape the value, then build the heading\n',
      solution: 'from html import escape\ndef render(title):\n    if not title.strip():\n        return 400, ""\n    return 200, "<h1>" + escape(title) + "</h1>"\nprint(render("<script>alert(1)</script>")[1])',
      solutionExplanation: "Validation and escaping happen before the tags are added, so the script text stays text inside the heading.",
      testCases: [{ label: "Escaped heading", expected: '<h1>&lt;script&gt;alert(1)&lt;/script&gt;</h1>' }],
      hints: ["Check the blank case first.", "Call escape on the title.", "Index the tuple to print the body."],
    },
    recap: ["Validation and escaping must happen before the value becomes markup.", "A status beside the body makes rejection explicit.", "Escaping is the boundary between data and markup."],
    decisionGuide: [
      { use: "escaping before concatenation", insteadOf: "escaping the finished HTML string", reason: "Once the value and tags are one string, no later replacement can tell them apart reliably." },
      { use: "returning status and body", insteadOf: "returning only a string", reason: "The caller needs to know whether the response is a rendering or a rejection." },
    ],
  },
  // Chapter 23
  23: {
    title: "Debug lab: cleanup that was skipped on an exception",
    minutes: 36,
    summary: "Repair a context manager whose teardown never ran when the block raised.",
    learningGoals: ["Explain what a context manager must guarantee", "Wrap the yield in try/finally", "Read missing teardown output as a cleanup failure"],
    explanation: "A context manager promises that teardown runs when the block ends, including when it ends badly. Code placed after the yield never runs if the block raises, so the resource is left open and the print that should prove the release never appears. try/finally restores the guarantee.",
    keywordNotes: ["Code after yield runs only when the block completes normally.", "finally runs on both the success and the failure path.", "A missing teardown line in the output is the evidence of the bug."],
    examples: [
      {
        title: "The teardown that never printed",
        code: 'from contextlib import contextmanager\n@contextmanager\ndef audit():\n    print("start")\n    yield\n    print("end")\ntry:\n    with audit():\n        raise ValueError("boom")\nexcept ValueError:\n    print("caught boom")',
        output: 'start\ncaught boom',
        explanation: "The exception travelled out of the with block and past the rest of the generator, so the cleanup print was skipped and only the caller's handler ran. Nothing raised a second error, which is why this kind of bug survives review.",
        reasons: [
          "contextmanager turns a generator into a context manager.",
          "The decorator applies that transformation to the function below.",
          "audit declares the boundary this example is about.",
          "Setup runs before the block and prints its own evidence.",
          "yield hands control to the block; whatever happens next decides whether the lines below run.",
          "This line is cleanup, but it sits on the success path only, which is the defect.",
          "The outer try keeps the example readable when the exception leaves the block.",
          "The failure is raised inside a with block so the teardown path is exercised.",
          "ValueError leaves the block, and the generator is discarded before the cleanup line.",
          "The caller catches the exception.",
          "The handler prints its own message, which is the only evidence left because the cleanup never ran.",
        ],
      },
      {
        title: "Release the resource in a finally",
        code: 'from contextlib import contextmanager\n@contextmanager\ndef audit():\n    print("start")\n    try:\n        yield\n    finally:\n        print("end")\ntry:\n    with audit():\n        raise ValueError("boom")\nexcept ValueError:\n    print("caught boom")',
        output: 'start\nend\ncaught boom',
        explanation: "The try/finally wraps the yield, so the exception leaves the block but the finally clause runs first. The output now shows setup, teardown in the right order, and the caller's recovery.",
        reasons: [
          "The import is unchanged.",
          "The decorator still converts the generator.",
          "The boundary keeps its name and purpose.",
          "Setup still prints before the block runs.",
          "try marks the region whose exit must be handled, however it happens.",
          "yield hands control to the block inside that protected region.",
          "finally names the code that runs on every exit, which is the repair.",
          "The release prints before the exception continues outward.",
          "The outer try keeps the example readable while still exercising the failure path.",
          "The failure still happens inside the with block.",
          "The exception travels out after cleanup has run.",
          "The caller catches it.",
          "The handler prints its message last, which is the visible difference from the broken version.",
        ],
      },
    ],
    exercise: {
      prompt: "Write an audit() context manager that prints start, yields, and prints end even when the block raises. Use it inside a try block that raises ValueError, and print caught boom.",
      starterCode: 'from contextlib import contextmanager\n# Guarantee the teardown on both paths\n',
      solution: 'from contextlib import contextmanager\n@contextmanager\ndef audit():\n    print("start")\n    try:\n        yield\n    finally:\n        print("end")\ntry:\n    with audit():\n        raise ValueError("boom")\nexcept ValueError:\n    print("caught boom")',
      solutionExplanation: "The finally clause runs before the exception leaves the block, so the release message appears between setup and recovery.",
      testCases: [{ label: "Teardown on the failure path", expected: 'start\nend\ncaught boom' }],
      hints: ["Put the yield inside a try block.", "Print end in the finally clause.", "Catch ValueError outside the with block."],
    },
    recap: ["A context manager's teardown must run on every exit.", "try/finally is what makes that promise true.", "Missing teardown output is the symptom to look for."],
    decisionGuide: [
      { use: "try/finally around the yield", insteadOf: "cleanup written after the yield", reason: "Only the finally clause runs when the block raises, so the plain version silently loses the release." },
      { use: "reading the output order", insteadOf: "assuming the block ended normally", reason: "The missing line between start and the handler is the whole diagnosis." },
    ],
  },
  // Chapter 24
  24: {
    title: "Debug lab: a swallowed failure that resurfaced elsewhere",
    minutes: 35,
    summary: "Repair a loader that returned None and left a confusing error for the caller.",
    learningGoals: ["Explain why a silent None is a costly contract", "Raise a domain error and chain the original cause", "Read a distant AttributeError as a symptom, not the cause"],
    explanation: "Returning None for a failed conversion pushes the failure forward: the caller receives a value that looks usable and fails somewhere unrelated, far from the text that was actually wrong. Raising a named error at the boundary keeps the failure at its source, and chaining with from keeps the original exception visible.",
    keywordNotes: ["ValueError raised from a parser failure keeps the diagnosis at the boundary.", "raise ... from error records the original cause for the traceback.", "None is a poor failure signal when every value in a range is meaningful."],
    examples: [
      {
        title: "The None that broke a later line",
        code: 'def load_port(text):\n    try:\n        return int(text)\n    except ValueError:\n        return None\nport = load_port("bad")\nprint(port)\ntry:\n    print(port.bit_length())\nexcept AttributeError as error:\n    print(type(error).__name__)',
        output: 'None\nAttributeError',
        explanation: "The loader answered None for unusable text, and the next line treated that None as an integer. The AttributeError happens two steps away from the real problem, which is the conversion that failed inside the loader.",
        reasons: [
          "load_port declares the helper that turns text into a port number.",
          "The conversion is the operation that can fail.",
          "A successful conversion returns the integer.",
          "The handler catches the failure.",
          "Returning None hides the failure behind a value that looks like data.",
          "The caller stores the result without checking what happened.",
          "The printed value is None, which is the first sign that something went wrong.",
          "The next line assumes an integer and asks it for a method.",
          "The second try is where the caller would have handled its own mistakes.",
          "None has no such method, so AttributeError is raised far from the conversion.",
          "The handler reports a failure that is really about the swallowed ValueError.",
        ],
      },
      {
        title: "Fail at the boundary with a named error",
        code: 'def load_port(text):\n    try:\n        return int(text)\n    except ValueError as error:\n        raise ValueError("port must be digits") from error\ntry:\n    load_port("bad")\nexcept ValueError as error:\n    print(type(error).__name__, "cause:", type(error.__cause__).__name__)',
        output: 'ValueError cause: ValueError',
        explanation: "The loader now raises at the point where the text was rejected, and the from clause keeps the original exception attached. The caller sees one error, at the right place, with its cause recorded.",
        reasons: [
          "The helper keeps its single responsibility.",
          "The conversion is still the operation that can fail.",
          "A good value still returns immediately.",
          "The handler now receives the original exception as a name it can use.",
          "A domain error is raised at the boundary, and from error records what actually went wrong.",
          "The caller is wrapped so the example can report the failure instead of stopping.",
          "The call supplies text the conversion rejects, which is the case being demonstrated.",
          "The caller catches the domain error.",
          "Both names are printed, showing the raised type and the recorded cause.",
        ],
      },
    ],
    exercise: {
      prompt: "Write load_port(text) that returns int(text) or raises ValueError(\"port must be digits\") from the original error. Then call it with \"bad\" and print the error type and its cause type.",
      starterCode: '# Keep the failure at the boundary and record its cause\n',
      solution: 'def load_port(text):\n    try:\n        return int(text)\n    except ValueError as error:\n        raise ValueError("port must be digits") from error\ntry:\n    load_port("bad")\nexcept ValueError as error:\n    print(type(error).__name__, "cause:", type(error.__cause__).__name__)',
      solutionExplanation: "Raising at the boundary keeps the failure where the bad text was rejected, and the cause records the original conversion error.",
      testCases: [{ label: "Named error with a cause", expected: 'ValueError cause: ValueError' }],
      hints: ["Catch ValueError as error.", "Use raise ... from error.", "Read error.__cause__ in the handler."],
    },
    recap: ["A silent None moves the failure away from its cause.", "A domain error at the boundary keeps the diagnosis local.", "raise ... from keeps the original exception available."],
    decisionGuide: [
      { use: "raising a domain error with a cause", insteadOf: "returning None for unusable input", reason: "The error stops the program where the problem is, while None lets it continue with unusable data." },
      { use: "reading __cause__", insteadOf: "printing only the new message", reason: "The cause names the original problem, which is often the most useful part of the report." },
    ],
  },
  // Chapter 25
  25: {
    title: "Debug lab: a shared default list in a data model",
    minutes: 34,
    summary: "Repair a dataclass whose field would have been shared by every instance.",
    learningGoals: ["Read the ValueError that names a mutable default", "Use default_factory for per-instance values", "Show that two instances no longer share state"],
    explanation: "A dataclass evaluates its field defaults once, at class definition, so a list default would be created a single time and handed to every instance. Python refuses that outright with ValueError rather than allowing a shared-state bug, and default_factory is the supported way to ask for a fresh list per object.",
    keywordNotes: ["default_factory calls a function for each new instance instead of sharing one value.", "dataclasses rejects a mutable default with ValueError because the state would be shared.", "Two instances created from the same class must not see each other's data."],
    examples: [
      {
        title: "A field that would be shared",
        code: 'from dataclasses import dataclass\ntry:\n    @dataclass\n    class Board:\n        tasks: list = []\nexcept ValueError as error:\n    print(type(error).__name__)',
        output: 'ValueError',
        explanation: "Python rejects the declaration because the list would be stored once and reused, which is the same shared-state defect as a mutable function default. The error arrives at class definition, before any instance exists.",
        reasons: [
          "dataclass is the decorator this example needs.",
          "try keeps the failure readable instead of ending with a traceback.",
          "The decorator would turn the class below into a data-carrying type.",
          "The class declares one field of the tasks the board holds.",
          "An empty list as a default would be evaluated once and shared, so Python refuses it.",
          "The refusal arrives as ValueError.",
          "The handler prints the type name, which identifies a declaration problem rather than a data problem.",
        ],
      },
      {
        title: "Ask for a fresh list per instance",
        code: 'from dataclasses import dataclass, field\n@dataclass\nclass Board:\n    tasks: list = field(default_factory=list)\nfirst = Board()\nsecond = Board()\nfirst.tasks.append("Build")\nprint(first.tasks)\nprint(second.tasks)',
        output: '[\'Build\']\n[]',
        explanation: "default_factory is called once for each new board, so the two instances own separate lists. Appending to the first board leaves the second untouched, which is the property the declaration now guarantees.",
        reasons: [
          "field is imported because it carries the per-instance rule.",
          "The decorator turns the class into a data model.",
          "The class keeps its name and its single field.",
          "default_factory=list is called for each instance, so no list is shared.",
          "The first board is constructed and receives its own list.",
          "The second board is constructed and receives a different list.",
          "One item is added to the first board only.",
          "The first board prints the item it stored.",
          "The second board still prints an empty list, which proves the instances are independent.",
        ],
      },
    ],
    exercise: {
      prompt: "Define a dataclass Board with tasks: list = field(default_factory=list). Create two boards, append \"Build\" to the first, and print both task lists.",
      starterCode: 'from dataclasses import dataclass, field\n# Give every instance its own list\n',
      solution: 'from dataclasses import dataclass, field\n@dataclass\nclass Board:\n    tasks: list = field(default_factory=list)\nfirst = Board()\nsecond = Board()\nfirst.tasks.append("Build")\nprint(first.tasks)\nprint(second.tasks)',
      solutionExplanation: "default_factory builds a new list for each board, so the two instances print separate task lists.",
      testCases: [{ label: "Per-instance lists", expected: '[\'Build\']\n[]' }],
      hints: ["Import field alongside dataclass.", "Pass default_factory=list.", "Print both instances to show the separation."],
    },
    recap: ["dataclasses refuses a mutable default so shared state cannot be written by accident.", "default_factory builds the value per instance.", "Printing two instances is the test that proves they do not share state."],
    decisionGuide: [
      { use: "field(default_factory=list)", insteadOf: "tasks: list = []", reason: "The factory produces a new list per object, while the plain default would be one list for the whole class." },
      { use: "constructing two instances in a test", insteadOf: "testing a single instance", reason: "Shared state is invisible until a second object exists." },
    ],
  },
};

export { pythonDebugLabs };
